server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Mohamed-Arshad/Spring-Cloud-Config-Store
          default-label: main #your repo branch
          search-paths:
           - '*service'
          #if you are using private repopository you should pass username and password
          #username: root
          #passphrase: 12345